/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VelocidadRouteImport } from './routes/velocidad'
import { Route as SoporteRouteImport } from './routes/soporte'
import { Route as PqrRouteImport } from './routes/pqr'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PlanesRouteImport } from './routes/planes'
import { Route as CoberturaRouteImport } from './routes/cobertura'
import { Route as IndexRouteImport } from './routes/index'

const VelocidadRoute = VelocidadRouteImport.update({
  id: '/velocidad',
  path: '/velocidad',
  getParentRoute: () => rootRouteImport,
} as any)
const SoporteRoute = SoporteRouteImport.update({
  id: '/soporte',
  path: '/soporte',
  getParentRoute: () => rootRouteImport,
} as any)
const PqrRoute = PqrRouteImport.update({
  id: '/pqr',
  path: '/pqr',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanesRoute = PlanesRouteImport.update({
  id: '/planes',
  path: '/planes',
  getParentRoute: () => rootRouteImport,
} as any)
const CoberturaRoute = CoberturaRouteImport.update({
  id: '/cobertura',
  path: '/cobertura',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cobertura': typeof CoberturaRoute
  '/planes': typeof PlanesRoute
  '/portal': typeof PortalRoute
  '/pqr': typeof PqrRoute
  '/soporte': typeof SoporteRoute
  '/velocidad': typeof VelocidadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cobertura': typeof CoberturaRoute
  '/planes': typeof PlanesRoute
  '/portal': typeof PortalRoute
  '/pqr': typeof PqrRoute
  '/soporte': typeof SoporteRoute
  '/velocidad': typeof VelocidadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cobertura': typeof CoberturaRoute
  '/planes': typeof PlanesRoute
  '/portal': typeof PortalRoute
  '/pqr': typeof PqrRoute
  '/soporte': typeof SoporteRoute
  '/velocidad': typeof VelocidadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cobertura'
    | '/planes'
    | '/portal'
    | '/pqr'
    | '/soporte'
    | '/velocidad'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cobertura'
    | '/planes'
    | '/portal'
    | '/pqr'
    | '/soporte'
    | '/velocidad'
  id:
    | '__root__'
    | '/'
    | '/cobertura'
    | '/planes'
    | '/portal'
    | '/pqr'
    | '/soporte'
    | '/velocidad'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoberturaRoute: typeof CoberturaRoute
  PlanesRoute: typeof PlanesRoute
  PortalRoute: typeof PortalRoute
  PqrRoute: typeof PqrRoute
  SoporteRoute: typeof SoporteRoute
  VelocidadRoute: typeof VelocidadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/velocidad': {
      id: '/velocidad'
      path: '/velocidad'
      fullPath: '/velocidad'
      preLoaderRoute: typeof VelocidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soporte': {
      id: '/soporte'
      path: '/soporte'
      fullPath: '/soporte'
      preLoaderRoute: typeof SoporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pqr': {
      id: '/pqr'
      path: '/pqr'
      fullPath: '/pqr'
      preLoaderRoute: typeof PqrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planes': {
      id: '/planes'
      path: '/planes'
      fullPath: '/planes'
      preLoaderRoute: typeof PlanesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cobertura': {
      id: '/cobertura'
      path: '/cobertura'
      fullPath: '/cobertura'
      preLoaderRoute: typeof CoberturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoberturaRoute: CoberturaRoute,
  PlanesRoute: PlanesRoute,
  PortalRoute: PortalRoute,
  PqrRoute: PqrRoute,
  SoporteRoute: SoporteRoute,
  VelocidadRoute: VelocidadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
